name: Safe Systems Juniper Log Parser
description: |
    Runs SyslogNG as a TLS endpoint on port 8000, parses logs, and sends UDP
version: v0.1
category: Monitoring
maintainer: Reid Riley <reid.riley@safesystems.com>
projectURL: http://www.safesystems.com
