logstash-config:
  restart: always
  image: safereg.azurecr.io/logstash-config
  log_opt:
    max-size: 50m
    max-file: 3
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: location=${service_location}
logstash:
  restart: always
  tty: true
  volumes_from:
  - logstash-config
  volumes:
    - /opt/safesystems/logs:/opt/safesystems/logs
  command:
  - logstash
  - -f
  - /etc/logstash/logstash.conf
  - --log.level=debug
  image: safereg.azurecr.io/logstash:test
  log_opt:
    max-size: 50m
    max-file: 3
  stdin_open: true
  environment:
    netcomply_id_var: "${netcomply_id}"
    aws_access_id_var: "${aws_access_id}"
    aws_secret_access_key_var: "${aws_secret_access_key}"
    aws_queue_name_var: "${aws_queue_name}"
    rad_location_var: "${service_location}"
  labels:
    io.rancher.sidekicks: logstash-config
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=${service_location}
