rancherhealth:
  restart: always
  tty: true
  image: safereg.azurecr.io/rancherhealth:latest
  log_opt:
    max-size: 50m
    max-file: 3
  stdin_open: true
  environment:
    netcomply_id_var: "${netcomply_id}"
    syslog_dest_host_var: "${syslog_dest_host}"
    rancher_api_key_var: "${rancher_api_key}"
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=${service_location}
