.catalog:
  name: "Safe Systems Rancher Health Check"
  version: "0.1-Test"
  description: "Checks the health of Rancher environments. Sends syslog alerts"
  questions:
    - variable: "syslog_dest_host"
      description: |
        syslog network destination
      label: "syslog_dest_host"
      type: "string"
      required: false
      default: ""
    - variable: "netcomply_id"
      description: |
        The AT ID of the Customer
      label: "AT ID"
      default: "enter AT_ID"
      required: false
      type: "string"
    - variable: "service_location"
      description: |
        This is location where the service will be deployed.
        This must match the location label value you entered for the host.
      label: "Service Location"
      type: "string"
      required: false
      default: |
        ""
    - variable: "rancher_api_key"
      description: |
        Enter your base64 encoded rancher key.
      label: "Base64 Rancher API Key"
      type: "string"
      required: true
      default: |
        ""
