name: Safe Systems Azure Site to Site VPN
description: |
    Azure Site to Site VPN
version: v0.1
category: Networking
maintainer: Reid Riley <reid.riley@safesystems.com>
projectURL: http://www.safesystems.com
