logstash:
  restart: always
  tty: true
  volumes:
    - /opt/safesystems/logstash/:/etc/logstash/
  command:
  - logstash
  - -f
  - /etc/logstash/conf.d/
  image: safesysreg.azurecr.io/logstashprocessor:latest
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
