static_router: 
  image: "safereg.azurecr.io/cloudrouter:test"
  log_opt:
    max-size: 50m
    max-file: 3
  labels: 
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=${service_location}
  tty: true
  restart: always
  privileged: true
  net: host
  environment:
    STATIC_ROUTE_TABLE: "${var_static_route_table}"
  volumes: 
    - "/lib/modules:/lib/modules:rw"